In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv('Back_Propagation_input.csv')
df

x1   x2     y
0  0.4 -0.7  0.1

In [45]:
Y = df.y
X = df.drop(columns='y')
X

x1   x2 
0  0.4 -0.7

In [57]:
class Back_Propagation():
    def __init__(self,alpha,beta):
        self.alpha = alpha
        self.beta = beta
        self.L = int(input('No. of neurons of input layer: '))
        self.M = int(input('No. of neurons of hidden layer: '))
        self.N = int(input('No. of neurons of output layer: '))
        self.initialize()
    
    def initialize(self):
        self.grad_V = np.zeros((self.L,self.M))# (L x M)
        self.grad_W = np.zeros((self.M,self.N))# (M x N)
        self.V_Matrix = np.empty((self.L,self.M))# (L x M)
        self.W_Matrix = np.empty((self.M,self.N))# (M x N)
        self.Error_arr = [] # (No. of Dp x 1)
        self.Y_Matrix = np.empty((self.M,1))
        # V_Matrix (L x M)
        print('Enter the weights of input to hidden layer..')
        for i in range(self.L):
            temp = []
            for j in range(self.M):
                temp.append(float(input()))
            self.V_Matrix[i] = temp    
            
        # W_Matrix (M x N)
        print('Enter the weights of hidden to output layer..')
        for i in range(self.M):
            temp = []
            for j in range(self.N):
                temp.append(float(input()))
            self.W_Matrix[i] = temp
        
            
    def fit(self, X: pd.DataFrame,Y: pd.Series):
        self.X = X
        self.Y = Y
        
        # Calculate input of hidden layer..
        #{I}h = <V> {O}i
        for index in range(len(X)):
            # Input of hidden layer...
            
            # (M x L) * (L x 1)
            # To convert  [0.54487889 0.50499983] - (1 x M) to
            # [  [0.54487889],
            #    [0.50499983]
            # ] - (M x 1)
            input_of_hidden_layer = []
            input_of_hidden_layer.append(np.dot(np.transpose(self.V_Matrix),X.iloc[index]))
            input_of_hidden_layer = np.transpose(input_of_hidden_layer)
            print('Input of hidden layer..')
            print(input_of_hidden_layer)
            # To convert  [0.54487889 0.50499983] - (1 x M) to
            # [  [0.54487889],
            #    [0.50499983]
            # ] - (M x 1)
            output_of_hidden_layer = self.activate(input_of_hidden_layer)
            print('Output of hidden layer..')
            print(output_of_hidden_layer)
            
            # (N x M) x (M x 1)
            input_of_output_layer = np.dot(np.transpose(self.W_Matrix),output_of_hidden_layer)
            print('Input of output layer..')
            print(input_of_output_layer)
            output_of_output_layer = self.activate(input_of_output_layer)
            print('Output of output layer..')
            print(output_of_output_layer)
            
            # Compute Error...
            print('Target: ',Y.iloc[index])
            self.Error_arr.append(np.sqrt(np.square(Y.iloc[index] - output_of_output_layer)))
            print(f'Error for dp{index+1}: ',self.Error_arr[index])

            # Finding D.....
            d = []
            d.append((Y.iloc[index] - output_of_output_layer[0]) * output_of_output_layer[0] * (1 - output_of_output_layer[0]))
            print('d',d)
            
            # Finding [Y]
            
            Y_matrix = np.dot(output_of_hidden_layer,d)
            print('Y_Matrix: ',Y_matrix)

            # Gradient W i.e. Gradient of weight of hidden to output layer..
            print('Shape: ',self.grad_W.shape)
            self.grad_W = np.dot(self.alpha,self.grad_W) + np.dot(self.beta,Y_matrix)
            print('Gradient w..')
            print(self.grad_W)

            # e = [w] * {d}
            e = np.dot(self.W_Matrix,d)
            print('e matrix..')
            print(e)

            # Step 11 - d_start_matrix (M x 1)
            d_star_matrix = []
            for j in range(len(e)):
                d_star_matrix.append([e[j][0] * output_of_hidden_layer[j][0] * (1-output_of_hidden_layer[j][0])])
            print('D Star matrix..')
            d_star_matrix = np.array(d_star_matrix)
            print(d_star_matrix)
            
            # step 12 - [X] = {O}I <d>
            # Converting 1 x n to n x 1
            temp = []
            temp.append(X.iloc[index])
            print('Temp..')
            print(np.transpose(temp).shape)
            X_Matrix = np.dot(np.transpose(temp),np.transpose(d_star_matrix))
            print('X matrix..')
            print(X_Matrix)

            # Step 13 - grad_v
            self.grad_V = np.dot(self.alpha,self.grad_V) + np.dot(self.beta,X_Matrix)
            print('Grad V...')
            print(self.grad_V)

            # Step 14 - V_matrix
            self.V_Matrix += self.grad_V
            print('V_matrix...')
            print(self.V_Matrix)

            # Step 15 - W_matrix
            self.W_Matrix +=self.grad_W
            print('W_matrix...')
            print(self.W_Matrix)
    
    def activate(self,x: list)->list:
        print('Sigmoid function...')
        return 1 / (1+np.exp(-x))        

In [58]:
model = Back_Propagation(0.1,0.6)
model.fit(X,Y)

No. of neurons of input layer:  2
No. of neurons of hidden layer:  2
No. of neurons of output layer:  1


Enter the weights of input to hidden layer..


 0.1
 0.4
 -0.2
 0.2


Enter the weights of hidden to output layer..


 0.2
 -0.5


Input of hidden layer..
[[0.18]
 [0.02]]
Sigmoid function...
Output of hidden layer..
[[0.54487889]
 [0.50499983]]
Input of output layer..
[[-0.14352414]]
Sigmoid function...
Output of output layer..
[[0.46418043]]
Target:  0.1
Error for dp1:  [[0.36418043]]
d [array([-0.09057785])]
Y_Matrix:  [[-0.04935396]
 [-0.0457418 ]]
Shape:  (2, 1)
Gradient w..
[[-0.02961237]
 [-0.02744508]]
e matrix..
[[-0.01811557]
 [ 0.04528892]]
D Star matrix..
[[-0.00449241]
 [ 0.0113211 ]]
Temp..
(2, 1)
X matrix..
[[-0.00179696  0.00452844]
 [ 0.00314468 -0.00792477]]
Grad V...
[[-0.00107818  0.00271706]
 [ 0.00188681 -0.00475486]]
V_matrix...
[[ 0.09892182  0.40271706]
 [-0.19811319  0.19524514]]
W_matrix...
[[ 0.17038763]
 [-0.52744508]]
